[package]
name = "pingclair-config"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Configuration parser for Pingclair (Pingclairfile)"

[dependencies]
pingclair-core = { path = "../pingclair-core" }
serde_json.workspace = true
thiserror.workspace = true
regex = "1"
ipnet.workspace = true
http.workspace = true

[dev-dependencies]
tempfile = "3"
proptest = "1"

[lints]
workspace = true
