worker_processes 2;
worker_rlimit_nofile 65535;

events {
    worker_connections 8192;
    use epoll;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log off;
    sendfile on;

    server {
        listen 9000 backlog=8192;
        server_name bench.local;
        root /var/www/html;

        location / {
            try_files $uri =404;
        }
    }
}
