[package]
name = "pingclair-fastcgi"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "FastCGI 1.1 protocol client for Pingclair"

[dependencies]
tokio.workspace = true
bytes.workspace = true
tracing.workspace = true
